### PR TITLE
Feature 1.2.7 - Various Bug Fixes

### LINKED ISSUE #72: Feature idea: $postfilter
Hi,

I have been thinking about #26 and came up with this idea:
The idea is a '$postfilter' that is applied after the linking of linked collections is done. 

**For example if I want to do a query for all persons in the city "Stockholm" with the book "Harry potter":** 
(Books is a linked collection)
```
Persons: {
   $filter: {city: 'Stockholm'},
   $postfilter: {Books.title: 'Harry potter'}
    firstname: 1,
   lastname: 1,
   city: 1,
   Books: {
      title: 1
      isbn: 1
  }
}
```

If each link also include a count of the number of linked documents we could also do this:
**We want to query all persons in the city "stockhom" with 3 books:**
(Books is a linked collection)
```
Persons: {
   $filter: {city: 'Stockholm'},
   $postfilter: {Books.$count: 3}
    firstname: 1,
   lastname: 1,
   city: 1,
   Books: {
      title: 1
      isbn: 1
  }
}
```
The use of $count would then solve #26 if you do:  Books.$count: {$gt: 0}

I understand that the postfilter will have to be done "in code" and not by MongoDB and therefore be less performant if you have a large dataset. It will also not work as expected if you use a $limit.

What do you think about this?
//Jonas

### LINKED ISSUE #100: When cleaningSelectors from a body-enforced exposure, make sure you treat nested values
If we have profile: 1, and the requested field is profile.firstName: 1, then it should be allowed.
Same applies to fields and filters.

https://github.com/cult-of-coders/grapher/blob/master/lib/exposure/lib/cleanSelectors.js#L24-L28

### LINKED ISSUE #102: If body function returns a special variable, it should allow the requester to get everything
For example, if the user is an admin or something, you just want to give him the right to do anything.

### LINKED ISSUE #109: Collection.expose() changes the behavior of collection.find() compared to Meteor core collection.find() which can lead to unexpected functionality changes compared to Meteor core
In a commit labeled "find(undefined) behaves diff from find(), fix":
https://github.com/meteor/meteor/blob/d93c021c896029d774ccecc7241ff20ec4045568/packages/mongo/collection.js#L304

find(undefined) and find() were made to do the same thing, return all documents in a collection by defaulting filter to {}.

But in Meteor core:
https://github.com/meteor/meteor/blob/d93c021c896029d774ccecc7241ff20ec4045568/packages/mongo/collection.js#L304

There is a note:
    // Collection.find() (return all docs) behaves differently
    // from Collection.find(undefined) (return 0 docs).  so be
    // careful about the length of arguments.

and Collection.find(undefined) returns 0 docs seemingly on purpose.

The issue with expose() changing how find(undefined) works in this way is that if a filter is accidentally undefined you have the possibility of returning ALL documents in a collection which can make a server run out of memory if the collection has hundreds of thousands of documents.

This would not be an issue writing a new app with only using expose, but we want to start utilizing grapher and we have over 3000 legacy non-grapher .finds in our app that were made under the "Collection.find(undefined) returns 0 docs" functionality that will now return all the documents in the collection instead of 0 docs now if an undefined slips through if we initialize expose on that collection.

It seems much safer to return 0 documents than all documents in a collection when undefined is the filter.

I was wondering if there was a specific reason for this, or if this change from Meteor core's .find was unintentional?

Thank you! :)

### LINKED ISSUE #112: Misleading Error Message Inversed Link
While I was defining an inverse link, I stumbled upon a misleading error message.

**Scenario:**
The `one-to-many` connection (Post -> Comments) with a typo in the name of the `inversedBy` field (`posts` instead of `post`) results into the following error message:

`Error: [You tried setting up an inversed link "posts" in "posts" to the "comments" collection that does not have any links defined] 
at packages/cultofcoders:grapher/lib/links/linker.js:209:27`

`Version: cultofcoders:grapher@1.2.6`

**MWE:**
```js
const Posts = new Mongo.Collection('posts');
const Comments = new Mongo.Collection('comments');

Posts.addLinks({
  comments: {
    collection: Comments,
    inversedBy: 'posts'
  }
})

Comments.addLinks({
  post: {
    type: 'one',
    collection: Posts,
    field: 'postId',
    index: true
  },
});
```

The error message is misleading in that sense, that the `comments` collection clearly has a link defined. I would suggest to rephrase it into something like the following:

`
You tried setting up an inversed link "posts" in "posts" linking to the "comments" collection, but there is no matching link with name "posts" in "comments".
`

Other than that, thanks for this beautiful package! 👍

### LINKED ISSUE #114: Update simple schema and collection2 deps?
Simple Schema and collection2 both have newer version that have moved to npm. I'd like to start updating to use these packages, but I'm currently constrained by grapher. It would be great if we could update the deps for grapher so that the new npm packages can be used instead of the older atmosphere ones. Thanks!

### PR DESCRIPTION
**Pull request by theodorDiaconu**
Fixes #114 
Fixes #102
Fixes #112 
Fixes #109
Fixes #72 
Fixes #100

### CODE REVIEW

File: lib/exposure/lib/cleanBody.js [hunk 1]
```diff
@@ -37,6 +37,12 @@ export default function cleanBody(main, second, ...args) {
             return;
         }
 
+        // we treat this specially, if the value is true
+        if (value === true) {
+            object[key] = _.isObject(secondValue) ? deepClone(secondValue) : value;
```
Comment (theodorDiaconu) [inline lib/exposure/lib/cleanBody.js]: ?

**Comment by theodorDiaconu** [comment]
https://github.com/aldeed/node-simple-schema/issues/65 weird simple schema issue :(
